import "../globals.css";
import styles from './styles.module.css'
import { Inter } from "next/font/google";
import Menu from "./Menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.main}>
          <Menu />
          {children}
        </div>
      </body>
    </html>
  );
}
